# Generated by Django 5.2.12 on 2026-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("action", models.CharField(max_length=100)),
                ("detail", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-ts"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "page_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q", models.CharField(db_index=True, max_length=255)),
                ("results", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
