# Generated by Django 5.2.12 on 2026-09-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title_zh", models.CharField(default="", max_length=255)),
                ("title_en", models.CharField(blank=True, default="", max_length=255)),
                ("description_zh", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                ("body_zh", models.TextField(blank=True, default="")),
                ("body_en", models.TextField(blank=True, default="")),
                ("business", models.CharField(default="general", max_length=50)),
                ("intent", models.CharField(default="I", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("reviewing", "待审核"),
                            ("published", "已发布"),
                            ("archived", "已下线"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "content_articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField()),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.contentarticle",
                    ),
                ),
            ],
            options={
                "db_table": "content_article_versions",
                "ordering": ["-version"],
                "unique_together": {("article", "version")},
            },
        ),
    ]
