# Generated by Django 5.1.15 on 2026-09-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
