# Generated by Django 5.2.12 on 2026-09-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("matter", models.CharField(max_length=50)),
                ("summary", models.TextField()),
                (
                    "country_or_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("language", models.CharField(default="zh", max_length=10)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新线索"),
                            ("contacted", "已联系"),
                            ("processing", "处理中"),
                            ("closed", "已结案"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "intakes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntakeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("storage_path", models.CharField(max_length=500)),
                ("size", models.BigIntegerField()),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="intakes.intake",
                    ),
                ),
            ],
            options={
                "db_table": "intake_files",
            },
        ),
    ]
